// Hidden setup shared by the playgrounds: the expense-claims table of the lesson.
const CLAIMS = `CREATE TABLE expense_claim (
  claim_id    integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  emp_id      integer NOT NULL REFERENCES employees (emp_id),
  receipt_no  text NOT NULL,
  claim_date  date NOT NULL DEFAULT DATE '2026-09-01',
  amount      numeric(12,2) NOT NULL CONSTRAINT chk_amount_positive CHECK (amount > 0),
  category    text NOT NULL CONSTRAINT chk_category CHECK (category IN ('Travel', 'Meals', 'Software')),
  status      text NOT NULL DEFAULT 'Submitted',
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_receipt UNIQUE (emp_id, receipt_no)
);
INSERT INTO expense_claim (emp_id, receipt_no, amount, category)
VALUES (1, 'R-001', 1500.50, 'Travel'), (2, 'R-002', 800.00, 'Meals');`;

export default {
  id: 'sql-ddl',
  title: 'CREATE TABLE and constraints: rules the database enforces',
  goal: 'You can design a table with the right data types and constraints (primary key, foreign key, UNIQUE, CHECK, NOT NULL, DEFAULT, identity, generated columns), change it safely with ALTER TABLE, and use views and materialized views.',
  roadmap: [
    'Data types, identity, DEFAULT, audit columns',
    'PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK, NOT NULL',
    'ALTER TABLE',
    'Views and materialized views',
  ],
  blocks: [
    `## The problem
So far the tables were given to you, with the data already in them. Now your team wants a new small system: **employee expense claims**. Employees submit claims with a receipt number, an amount and a category, and a manager approves them. Somebody has to decide what the table looks like.

It matters more than it seems. Remember what the Kollana data taught you. **Order 77 belongs to customer 99, who does not exist.** Some GL lines were loaded twice. A payables line carries a debit that does not belong there. All of these got into the data because nothing **stopped** them. A **constraint** is a rule that the database checks on **every** \`INSERT\` and \`UPDATE\`, whoever sends it: your Python script, a Power Automate flow, an ETL job, or a person with DBeaver on a Friday evening. Rules in application code are skipped by whoever did not read the application. Rules in the table are enforced for everybody.

This lesson is about \`CREATE TABLE\`: the **types**, the **constraints**, how to change a table later without breaking anything, and the **views** that give other people a safe way to read it.`,
    `## Choosing data types
| Type | Use it for | Avoid |
|---|---|---|
| \`integer\`, \`bigint\` | ids, counts, quantities (use \`bigint\` when a table may pass two billion rows) | |
| \`numeric(12,2)\` | **money** and anything that must be exact: 12 digits in total, 2 after the point | \`real\` and \`double precision\` for money: floating point cannot store 0.1 exactly |
| \`text\` | any text. PostgreSQL stores it as efficiently as a limited type | \`char(n)\` (it pads with spaces). Use \`varchar(n)\` only when the limit is a real business rule |
| \`boolean\` | yes/no flags | text columns holding 'Y' and 'N' |
| \`date\` | a calendar day (invoice date, hire date) | text such as '31/03/2026' |
| \`timestamptz\` | a moment in time (created at, paid at) | \`timestamp\` without a time zone |
| \`jsonb\` | uneven or nested documents | JSON for fields you filter on constantly |
| \`uuid\` | ids created by many systems without clashing | |

For ids, use an **identity column**: \`claim_id integer GENERATED ALWAYS AS IDENTITY\`. The database hands out the next number, and \`ALWAYS\` stops anyone from inserting an id by hand. (\`serial\` is the older spelling of the same idea. \`GENERATED BY DEFAULT\` allows manual ids, which you need when loading data that already has ids.) Remember from the transactions lesson that identity numbers can have **gaps**.

## Constraints: the six rules
Here is the table the system needs, with every rule coloured by kind:`,
    { sketch: { w: 760, h: 302, caption: 'One CREATE TABLE statement and the rules inside it. The database checks every colour on every INSERT and UPDATE.', items: [
      { t: 'text', x: 14, y: 26, text: 'CREATE TABLE expense_claim (', size: 14, anchor: 'start', font: 'mono' },
      { t: 'text', x: 14, y: 52, text: '  claim_id   integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,', size: 14, anchor: 'start', font: 'mono', color: '#2f9e44' },
      { t: 'text', x: 14, y: 78, text: '  emp_id     integer NOT NULL REFERENCES employees (emp_id),', size: 14, anchor: 'start', font: 'mono', color: '#1971c2' },
      { t: 'text', x: 14, y: 104, text: '  receipt_no text    NOT NULL,', size: 14, anchor: 'start', font: 'mono', color: '#6741d9' },
      { t: 'text', x: 14, y: 130, text: '  amount     numeric(12,2) NOT NULL CHECK (amount > 0),', size: 14, anchor: 'start', font: 'mono', color: '#e8590c' },
      { t: 'text', x: 14, y: 156, text: '  category   text    NOT NULL CHECK (category IN (...)),', size: 14, anchor: 'start', font: 'mono', color: '#e8590c' },
      { t: 'text', x: 14, y: 182, text: '  created_at timestamptz NOT NULL DEFAULT now(),', size: 14, anchor: 'start', font: 'mono', color: '#0c8599' },
      { t: 'text', x: 14, y: 208, text: '  CONSTRAINT uq_receipt UNIQUE (emp_id, receipt_no)', size: 14, anchor: 'start', font: 'mono', color: '#c2255c' },
      { t: 'text', x: 14, y: 234, text: ');', size: 14, anchor: 'start', font: 'mono' },
      { t: 'text', x: 640, y: 40, text: 'PRIMARY KEY', size: 16, anchor: 'start', bold: true, color: '#2f9e44' },
      { t: 'text', x: 640, y: 76, text: 'FOREIGN KEY', size: 16, anchor: 'start', bold: true, color: '#1971c2' },
      { t: 'text', x: 640, y: 112, text: 'NOT NULL', size: 16, anchor: 'start', bold: true, color: '#6741d9' },
      { t: 'text', x: 640, y: 148, text: 'CHECK', size: 16, anchor: 'start', bold: true, color: '#e8590c' },
      { t: 'text', x: 640, y: 184, text: 'DEFAULT', size: 16, anchor: 'start', bold: true, color: '#0c8599' },
      { t: 'text', x: 640, y: 220, text: 'UNIQUE', size: 16, anchor: 'start', bold: true, color: '#c2255c' },
      { t: 'note', x: 14, y: 246, w: 732, h: 48, fill: 'yellow', size: 15, text: 'A rule in the table is checked for every program, flow and person.\nA rule in application code is checked only by that application.' },
    ] } },
    `| Constraint | What it guarantees | When you break it, the message starts like this |
|---|---|---|
| \`PRIMARY KEY\` | every row has an id that is **unique and not NULL** | *duplicate key value violates unique constraint* |
| \`FOREIGN KEY … REFERENCES\` | the value **exists in the parent table** | *insert or update … violates foreign key constraint* |
| \`UNIQUE\` | no two rows have the same value (or the same **combination** of values) | *duplicate key value violates unique constraint* |
| \`CHECK (condition)\` | every row satisfies a condition | *new row … violates check constraint* |
| \`NOT NULL\` | a value is required | *null value in column … violates not-null constraint* |
| \`DEFAULT value\` | not a check: the value used when none is given | |

Details that matter:
- **Name your constraints** (\`CONSTRAINT chk_amount_positive CHECK …\`). The name appears in the error message, so *violates check constraint "chk_amount_positive"* tells the person exactly what went wrong. Unnamed constraints get a generated name like \`expense_claim_amount_check\`.
- \`UNIQUE (emp_id, receipt_no)\` means the **pair** must be unique: the same receipt number may be used by two employees, but not twice by one. A \`UNIQUE\` constraint allows several NULLs, because two NULLs are "not equal". (PostgreSQL 15 added \`UNIQUE NULLS NOT DISTINCT\` if you want one NULL only.)
- A \`CHECK\` is for rules about **one row**. It cannot look at other rows or other tables. Rules across rows need a unique index, a trigger, or the transaction tricks from the last lessons.
- A **foreign key** also protects the **parent**: you cannot delete an employee who still has claims. What should happen is your choice, with \`ON DELETE\`. The default (\`NO ACTION\`, which behaves like \`RESTRICT\`) refuses the delete.`,
    { sketch: { w: 760, h: 195, caption: 'The three common choices for what a foreign key does when the parent row is deleted. Example: delete the employee who owns two claims.', items: [
      { t: 'table', x: 15, y: 48, title: 'ON DELETE ...', cols: ['option', 'what happens to the 2 claims', 'use it when'], colW: [252, 250, 228], rows: [['RESTRICT / NO ACTION (default)', 'the delete fails with an error', 'history must be kept'], ['CASCADE', 'the claims are deleted too', 'children mean nothing alone'], ['SET NULL', 'claims stay, emp_id = NULL', 'the link is optional']], hl: [0] },
      { t: 'note', x: 15, y: 156, w: 730, h: 30, fill: 'yellow', size: 14, text: 'For finance data the safe choice is the default. Cascading deletes can erase a ledger in one statement.' },
    ] } },
    { sql: {
      title: 'Create the table, then try to break every rule',
      starter: `-- The table of the lesson, created from scratch (employees already exists)
CREATE TABLE expense_claim (
  claim_id    integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  emp_id      integer NOT NULL REFERENCES employees (emp_id),
  receipt_no  text NOT NULL,
  claim_date  date NOT NULL DEFAULT DATE '2026-09-01',
  amount      numeric(12,2) NOT NULL CONSTRAINT chk_amount_positive CHECK (amount > 0),
  category    text NOT NULL CONSTRAINT chk_category CHECK (category IN ('Travel', 'Meals', 'Software')),
  status      text NOT NULL DEFAULT 'Submitted',
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_receipt UNIQUE (emp_id, receipt_no)
);

-- Two good claims: the id, the date and the status are filled in by the database
INSERT INTO expense_claim (emp_id, receipt_no, amount, category)
VALUES (1, 'R-001', 1500.50, 'Travel'), (2, 'R-002', 800.00, 'Meals')
RETURNING claim_id, claim_date, status;

-- Seven bad claims. A DO block (explained in the programmability module) tries each one,
-- catches the error and writes its message into a table, so we can see them all at once.
CREATE TABLE constraint_tests (n serial, test text, error_message text);
DO $$
BEGIN
  BEGIN INSERT INTO expense_claim (emp_id, receipt_no, amount, category) VALUES (999, 'R-X1', 100, 'Travel');
  EXCEPTION WHEN OTHERS THEN INSERT INTO constraint_tests (test, error_message) VALUES ('employee 999 does not exist', SQLERRM); END;
  BEGIN INSERT INTO expense_claim (emp_id, receipt_no, amount, category) VALUES (1, 'R-X2', -5, 'Travel');
  EXCEPTION WHEN OTHERS THEN INSERT INTO constraint_tests (test, error_message) VALUES ('negative amount', SQLERRM); END;
  BEGIN INSERT INTO expense_claim (emp_id, receipt_no, amount, category) VALUES (1, 'R-X3', 100, 'Holiday');
  EXCEPTION WHEN OTHERS THEN INSERT INTO constraint_tests (test, error_message) VALUES ('category not in the list', SQLERRM); END;
  BEGIN INSERT INTO expense_claim (emp_id, receipt_no, amount, category) VALUES (1, 'R-001', 100, 'Travel');
  EXCEPTION WHEN OTHERS THEN INSERT INTO constraint_tests (test, error_message) VALUES ('same receipt twice for one employee', SQLERRM); END;
  BEGIN INSERT INTO expense_claim (emp_id, receipt_no, amount, category) VALUES (NULL, 'R-X5', 100, 'Travel');
  EXCEPTION WHEN OTHERS THEN INSERT INTO constraint_tests (test, error_message) VALUES ('no employee', SQLERRM); END;
  BEGIN INSERT INTO expense_claim (emp_id, receipt_no, amount, category) VALUES (1, 'R-X6', 12345678901.00, 'Travel');
  EXCEPTION WHEN OTHERS THEN INSERT INTO constraint_tests (test, error_message) VALUES ('amount too large for numeric(12,2)', SQLERRM); END;
  BEGIN INSERT INTO expense_claim (emp_id, receipt_no, amount, category) VALUES (1, 'R-X7', 'abc', 'Travel');
  EXCEPTION WHEN OTHERS THEN INSERT INTO constraint_tests (test, error_message) VALUES ('amount is not a number', SQLERRM); END;
END $$;

SELECT test, error_message FROM constraint_tests ORDER BY n;

-- None of the seven bad rows got in
SELECT COUNT(*) AS claims_in_table FROM expense_claim;`,
      note: 'The two good claims get the ids 1 and 2, the date 2026-09-01 and the status Submitted automatically. All seven bad inserts are refused, each with its own message: a foreign key violation, the two named CHECK constraints, a duplicate key on uq_receipt, a not-null violation, "numeric field overflow" and "invalid input syntax for type numeric". The table still holds exactly 2 claims.',
    } },
    `## Audit columns and generated columns
Most business tables carry a few **audit columns**: \`created_at timestamptz NOT NULL DEFAULT now()\`, often \`created_by text DEFAULT current_user\`, and an \`updated_at\` that a trigger or the application keeps current (the programmability module shows the trigger). They answer "who changed this, and when?" when somebody asks a month later. A \`deleted_at\` column instead of a real \`DELETE\` gives you a **soft delete**.

A **generated column** is calculated by the database from other columns and cannot be written by hand: \`gross numeric GENERATED ALWAYS AS (amount * 1.18) STORED\`. It can never drift out of step with its inputs, and a program that tries to \`UPDATE\` it gets *column "gross" can only be updated to DEFAULT*.

## ALTER TABLE: changing a table that holds data
Tables change over time. The commands you will use:

| Change | Statement |
|---|---|
| add a column | \`ALTER TABLE t ADD COLUMN currency char(3) NOT NULL DEFAULT 'INR'\` (fast, even on big tables) |
| rename | \`ALTER TABLE t RENAME COLUMN status TO claim_status\` |
| change a type | \`ALTER COLUMN receipt_no TYPE integer USING regexp_replace(receipt_no, '[^0-9]', '', 'g')::int\` (the \`USING\` says how to convert the old values) |
| make a column required | \`ALTER COLUMN approved_by SET NOT NULL\` |
| add a rule | \`ADD CONSTRAINT chk_status CHECK (…)\` |
| remove | \`DROP COLUMN\`, \`DROP CONSTRAINT\` |

The thing to remember is that a new rule must be true for the rows that **already exist**. If it is not, the statement fails and nothing changes: *check constraint "chk_big" of relation "expense_claim" is violated by some row*, or *column "approved_by" of relation "expense_claim" contains null values*. Clean the data first (the safe routine from the DML lesson), then add the rule. On a very large table, \`ADD CONSTRAINT … NOT VALID\` adds the rule for **new** rows at once and \`VALIDATE CONSTRAINT\` checks the old rows later with a lighter lock. Note that a \`NOT VALID\` constraint is **already enforced for new rows**, so it can reject inserts straight away.

Two warnings from earlier lessons apply. Most forms of \`ALTER TABLE\` need the **\`ACCESS EXCLUSIVE\`** lock, so run them with \`SET lock_timeout\` and at a quiet time. And because **DDL is transactional in PostgreSQL**, you can wrap a migration in \`BEGIN … COMMIT\`: if any step fails, the whole migration is undone. Keep every change as a **numbered script in Git** (\`001_create_expense_claim.sql\`, \`002_add_currency.sql\`), never as a one-off command typed into a tool.`,
    { sql: {
      title: 'Changing the table safely',
      setup: CLAIMS,
      starter: `-- Add columns: a nullable one, and a required one with a default for the rows that exist
ALTER TABLE expense_claim ADD COLUMN approved_by integer REFERENCES employees (emp_id);
ALTER TABLE expense_claim ADD COLUMN currency char(3) NOT NULL DEFAULT 'INR';
ALTER TABLE expense_claim RENAME COLUMN status TO claim_status;

-- Convert a text column to a number, telling PostgreSQL how (R-001 becomes 1)
ALTER TABLE expense_claim
  ALTER COLUMN receipt_no TYPE integer
  USING regexp_replace(receipt_no, '[^0-9]', '', 'g')::int;

-- A generated column: the database keeps it correct
ALTER TABLE expense_claim ADD COLUMN gross numeric GENERATED ALWAYS AS (amount * 1.18) STORED;

-- Which new rules would the existing rows break? Try each one and record the message.
CREATE TABLE migration_tests (n serial, step text, result text);
DO $$
BEGIN
  BEGIN ALTER TABLE expense_claim ADD CONSTRAINT chk_big CHECK (amount > 1000);
    INSERT INTO migration_tests (step, result) VALUES ('CHECK amount > 1000', 'added');
  EXCEPTION WHEN OTHERS THEN INSERT INTO migration_tests (step, result) VALUES ('CHECK amount > 1000', SQLERRM); END;
  BEGIN ALTER TABLE expense_claim ALTER COLUMN approved_by SET NOT NULL;
    INSERT INTO migration_tests (step, result) VALUES ('approved_by NOT NULL', 'added');
  EXCEPTION WHEN OTHERS THEN INSERT INTO migration_tests (step, result) VALUES ('approved_by NOT NULL', SQLERRM); END;
  BEGIN UPDATE expense_claim SET gross = 1 WHERE claim_id = 1;
    INSERT INTO migration_tests (step, result) VALUES ('write a generated column', 'allowed');
  EXCEPTION WHEN OTHERS THEN INSERT INTO migration_tests (step, result) VALUES ('write a generated column', SQLERRM); END;
END $$;

SELECT step, result FROM migration_tests ORDER BY n;
SELECT claim_id, receipt_no, amount, gross, currency, claim_status FROM expense_claim ORDER BY claim_id;

-- Inspect the table the way a DBA does
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'expense_claim'
ORDER BY ordinal_position;`,
      note: 'The first two rules are refused: one claim has an amount of 800 (the CHECK is violated by some row) and the new approved_by column is NULL for both rows (the column contains null values). The generated column cannot be written ("can only be updated to DEFAULT"). The claims show the converted receipt numbers 1 and 2, a gross of 1770.59 and 944.00 (printed with four decimals, because 1.18 has two more), the currency INR and the status column now called claim_status.',
    } },
    `## Views and materialized views
A **view** is a **saved query** with a name. It stores no data. Every time you read it, PostgreSQL runs the query. A view gives you:
- **simplicity**: the five-table join is written once, and everybody selects from \`v_open_claims\`;
- **safety**: expose only the columns and rows a team may see (the security lesson builds on this);
- **a stable contract**: the underlying tables can change while the view keeps its shape.

A **materialized view** stores the **result** of the query, like a table that you refresh. Reading it is fast (the work was done earlier), but the data is **as old as the last refresh**. You refresh it with \`REFRESH MATERIALIZED VIEW name\`, which locks readers out while it works, or \`REFRESH MATERIALIZED VIEW CONCURRENTLY name\`, which keeps readers working but needs a **unique index** on the view.

| | View | Materialized view |
|---|---|---|
| Stores data | no | yes |
| Always current | yes | no, until refreshed |
| Cost of reading | runs the query each time | like reading a table |
| Good for | simplifying, security, current data | heavy reports read often (month-end summaries) |

\`CREATE TABLE AS\` makes a plain table from a query result. It is a snapshot with no link to its source, which is useful for scratch work and for backups before a risky fix.`,
    { sql: {
      title: 'A view is always current, a materialized view is a snapshot',
      setup: CLAIMS,
      starter: `-- A view: a saved query, always reading the current data
CREATE VIEW v_open_claims AS
SELECT c.claim_id, e.emp_name, c.amount, c.status
FROM expense_claim c
JOIN employees e USING (emp_id)
WHERE c.status = 'Submitted';

-- A materialized view: a stored result
CREATE MATERIALIZED VIEW mv_claims_by_employee AS
SELECT emp_id, COUNT(*) AS claims, SUM(amount) AS total
FROM expense_claim
GROUP BY emp_id;

-- A new claim arrives
INSERT INTO expense_claim (emp_id, receipt_no, amount, category) VALUES (1, 'R-003', 250.00, 'Meals');

SELECT * FROM v_open_claims ORDER BY claim_id;                        -- shows the new claim (3 rows)
SELECT * FROM mv_claims_by_employee ORDER BY emp_id;                  -- still the OLD totals

REFRESH MATERIALIZED VIEW mv_claims_by_employee;
SELECT * FROM mv_claims_by_employee ORDER BY emp_id;                  -- now includes the new claim

-- CONCURRENTLY needs a unique index on the materialized view
CREATE UNIQUE INDEX ux_mv_claims_emp ON mv_claims_by_employee (emp_id);
REFRESH MATERIALIZED VIEW CONCURRENTLY mv_claims_by_employee;`,
      note: 'The view shows all three claims at once. The materialized view still shows employee 1 with 1 claim and 1,500.50 until it is refreshed, and then shows 2 claims and 1,750.50. The concurrent refresh works once the unique index exists. Rows in a materialized view are only as fresh as its last refresh, so a report built on one should print that time.',
    } },
    `## Reading the design back
The database knows its own design, and you can ask it. \`information_schema.columns\` lists columns and their types, \`information_schema.table_constraints\` the constraints, and \`pg_constraint\` (with \`pg_get_constraintdef\`) the full rule text. In \`psql\` the shortcut is \`\\d expense_claim\`. Data engineers use these queries for **design reviews**: which tables have no primary key, which foreign keys exist, which money columns are not \`numeric\`. PostgreSQL 18 also lists \`NOT NULL\` as a named constraint, like the others.`,
    `## Practice
These challenges read the **catalog** of the Kollana database. They are the review queries a data engineer runs when a new database lands on the desk.`,
    { challenge: {
      id: 'sql-ddl-ch1',
      level: 'easy',
      ordered: true,
      prompt: 'Design review: which tables in the `public` schema have **no primary key**? Return `table_name`, sorted by `table_name`. (2 rows: `fact_budget` and `payroll`.) Look only at ordinary tables (`table_type = \'BASE TABLE\'` in `information_schema.tables`).',
      hint: "Start from information_schema.tables for schema 'public' and 'BASE TABLE', then NOT EXISTS (SELECT 1 FROM information_schema.table_constraints c WHERE same schema and table, c.constraint_type = 'PRIMARY KEY').",
      solution: `SELECT t.table_name
FROM information_schema.tables t
WHERE t.table_schema = 'public'
  AND t.table_type = 'BASE TABLE'
  AND NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints c
    WHERE c.table_schema = t.table_schema
      AND c.table_name = t.table_name
      AND c.constraint_type = 'PRIMARY KEY'
  )
ORDER BY t.table_name`,
    } },
    { challenge: {
      id: 'sql-ddl-ch2',
      level: 'medium',
      ordered: true,
      prompt: 'List the **foreign keys** of the `public` schema: `child_table, column_name, parent_table`, sorted by `child_table`, then `column_name`. (4 rows: `dim_account.parent_account_id` and the three `fact_gl` columns.) Use `pg_constraint` (`contype = \'f\'`); `conrelid::regclass::text` gives the child table name, `confrelid::regclass::text` the parent, and `conkey` holds the column numbers.',
      hint: "FROM pg_constraint c JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey) WHERE c.contype = 'f' AND c.connamespace = 'public'::regnamespace.",
      solution: `SELECT c.conrelid::regclass::text AS child_table,
       a.attname AS column_name,
       c.confrelid::regclass::text AS parent_table
FROM pg_constraint c
JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
WHERE c.contype = 'f'
  AND c.connamespace = 'public'::regnamespace
ORDER BY child_table, column_name`,
    } },
    { challenge: {
      id: 'sql-ddl-ch3',
      level: 'medium',
      ordered: true,
      prompt: 'Money review. List every column of type `numeric` in the `public` schema with its precision and scale: `table_name, column_name, numeric_precision, numeric_scale`, sorted by `table_name`, then `column_name`. (13 rows.) This is the inventory you check against "no floating point for money".',
      hint: "information_schema.columns WHERE table_schema = 'public' AND data_type = 'numeric'.",
      solution: `SELECT table_name, column_name, numeric_precision, numeric_scale
FROM information_schema.columns
WHERE table_schema = 'public'
  AND data_type = 'numeric'
ORDER BY table_name, column_name`,
    } },
    { real: 'Treat the table definition as **the first line of data quality**. The cheapest bug to fix is the one that cannot happen: put `NOT NULL`, `CHECK`, `UNIQUE` and foreign keys in the table instead of hoping every loader behaves. When an ingestion step violates a rule, that is a **feature**: the row goes to an exceptions table and a person looks at it, instead of a wrong number reaching a report. Keep every table in a numbered migration script in Git, review it like code, and test it on a copy first. And give each team a **view** (or a materialized view for the heavy ones) instead of access to the raw tables.' },
    { interview: '"What constraints does PostgreSQL support, and when would you use a materialized view instead of a view?" Model answer: "NOT NULL, DEFAULT, PRIMARY KEY, UNIQUE, CHECK and FOREIGN KEY with ON DELETE options, plus exclusion constraints for ranges. I name the constraints so that error messages are clear, and I use numeric for money and timestamptz for moments. A view is a saved query that always shows current data and stores nothing. A materialized view stores the result, so reads are fast, but it is stale until I refresh it, and a concurrent refresh needs a unique index. I use a materialized view for a heavy report that many people read and that can be a few hours old." Follow-ups: "How do you add a NOT NULL column to a big table?" (add it with a DEFAULT, which is fast, or add it nullable, backfill in batches, then SET NOT NULL) and "what does ON DELETE CASCADE do and when is it dangerous?" (deletes the children with the parent, so it can erase history).' },
    `## Recap
- Constraints are rules the **database** enforces for every writer: \`PRIMARY KEY\`, \`FOREIGN KEY\`, \`UNIQUE\`, \`CHECK\`, \`NOT NULL\`, plus \`DEFAULT\` for missing values. Name them, so the error message explains itself. Order 77 and customer 99 could not have happened with a foreign key.
- Types: \`numeric(12,2)\` for money, \`text\`, \`date\`, \`timestamptz\`, \`boolean\`, identity columns for ids (with possible gaps). Audit columns (\`created_at\`, \`updated_at\`, \`deleted_at\`) say who and when. Generated columns cannot drift.
- \`ALTER TABLE\` changes a table, but a new rule must hold for the rows that already exist. Clean first. \`NOT VALID\` plus \`VALIDATE CONSTRAINT\` eases big tables. \`ALTER\` needs \`ACCESS EXCLUSIVE\`, so use \`lock_timeout\`. DDL is transactional, so wrap migrations in \`BEGIN … COMMIT\` and keep them as numbered scripts in Git.
- \`ON DELETE\`: the default refuses the delete, \`CASCADE\` deletes the children, \`SET NULL\` keeps them without a link.
- A **view** is a saved query, always current. A **materialized view** stores the result, needs \`REFRESH\` (and a unique index for \`CONCURRENTLY\`) and shows old data until then.
- \`information_schema\` and \`pg_constraint\` let you review a design with SQL: tables without a primary key (\`fact_budget\`, \`payroll\`), the four foreign keys, the 13 numeric columns.`,
  ],
  quiz: [
    { q: 'Why give a constraint a name, as in `CONSTRAINT chk_amount_positive CHECK (amount > 0)`?', o: ['The name makes the check run faster', 'The name appears in the error message, so the person knows which rule was broken', 'PostgreSQL requires every constraint to have a name', 'Named constraints cannot be dropped'], a: 1, why: 'The message reads "violates check constraint chk_amount_positive". An unnamed one gets a generated name like expense_claim_amount_check, which says less.' },
    { q: 'Which type should you use for an invoice amount?', o: ['real', 'double precision', 'text', 'numeric(12,2)'], a: 3, why: 'numeric stores decimals exactly. Floating-point types cannot store 0.1 exactly and give results such as 0.30000000000000004.' },
    { q: 'You try to add `CHECK (amount > 1000)` to a table where one row has an amount of 800. What happens?', o: ['The statement fails and the table is unchanged, because the new rule must hold for the existing rows', 'The check is added and the row is deleted', 'The check is added and applies only to new rows', 'PostgreSQL changes the amount to 1000'], a: 0, why: 'ALTER TABLE ADD CONSTRAINT validates existing rows and refuses when some break the rule. (NOT VALID defers the check of old rows, but enforces the rule for new ones at once.)' },
    { q: 'What does the default `ON DELETE` behaviour of a foreign key do when you delete a parent row that has child rows?', o: ['It deletes the child rows too', 'It sets the child column to NULL', 'It refuses the delete with an error', 'It does nothing and leaves orphans'], a: 2, why: 'The default (NO ACTION, which acts like RESTRICT) protects the children by rejecting the delete. CASCADE and SET NULL must be chosen on purpose.' },
    { q: 'A materialized view shows old totals after new rows were inserted. Why?', o: ['Materialized views cannot read tables', 'It stores the result of its query and is only refreshed by REFRESH MATERIALIZED VIEW', 'The insert was rolled back', 'Views always show old data'], a: 1, why: 'A materialized view is a stored snapshot. A plain view runs its query every time and is always current.' },
    { q: 'What does `REFRESH MATERIALIZED VIEW CONCURRENTLY` require?', o: ['A foreign key on the view', 'A primary key on the base table', 'The view must be empty', 'A unique index on the materialized view'], a: 3, why: 'To update the view while readers keep reading it, PostgreSQL compares old and new rows by a unique key, so the view needs a unique index.' },
  ],
  task: {
    title: 'Build and migrate the expense table on your laptop',
    steps: [
      'In DBeaver (database fde_practice), create `23_ddl.sql` in `C:\\sql-practice`. Create `expense_claim` exactly as in the lesson, with named constraints, and insert the two good claims.',
      'Run the seven bad inserts one at a time, in autocommit mode (a failed statement changes nothing), and write each error message in a comment. Confirm that the table still has 2 rows.',
      'Write two numbered migration scripts as comments in the file: `001` adds `approved_by` and `currency`, `002` renames `status` to `claim_status` and adds the `gross` generated column. Run them inside `BEGIN … COMMIT`, and then show that a failing step (an `ADD CONSTRAINT CHECK (amount > 1000)`) rolls the whole migration back.',
      'Create `v_open_claims` and the materialized view `mv_claims_by_employee`. Insert one more claim and show the difference between them before and after the refresh. Add the unique index and run the concurrent refresh.',
      'Run the three review queries on the Kollana tables (tables without a primary key, foreign keys, numeric columns) and write what you would change in that design.',
    ],
    deliverable: '`23_ddl.sql` with the table, the seven error messages, two migration scripts, the views and the three catalog queries with their results.',
  },
};
